---
- hosts: server
  become: true
  tasks:
    - name: isntall of git
      yum:
        name: git
        state: present
    - name: user creation
      user:
         name: prasanta
         state: present
