---
- hosts: server
  become: true
  tasks:
    - name: isntall of git
      yum:
        name: git
        state: present
    - name: user creation
      user:
         name: prasanta
         state: present
    - name: httpd installation
      yum:
        name: httpd
        state: present
    - name: make up
      service:
        name: httpd 
        state: started
